version: "3.9"  

services:
  users_db:
    image: postgres:15  
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data:  